import { defineConfig } from '@playwright/test';

/**
 * playwright.config.ts
 * ─────────────────────
 * Central configuration for all Playwright E2E runs.
 *
 * REPORT ARCHITECTURE
 * ───────────────────
 * Reports are generated by tests/versioned-reporter.ts — a custom Reporter
 * class registered below. It writes specs/<slug>/report-v{N}.html in its
 * onEnd() callback, using in-memory data collected during the run.
 *
 * globalTeardown is NOT used for reports. It is not registered here.
 *
 * FILE NAMING CONVENTION
 * ──────────────────────
 *   tests/e2e/<feature-slug>.spec.ts  →  specs/<feature-slug>/report-v{N}.html
 *   report-v1.html  = first automated run
 *   report-v2.html  = second run, and so on
 *   report.html     = manual live-verification report (never overwritten)
 */

export default defineConfig({
  testDir: './tests/e2e',

  // ── Execution ───────────────────────────────────────────────────────────────
  maxFailures:   0,     // NEVER stop early — every test always runs
  // One retry in CI SURFACES flakiness: Playwright marks such tests "flaky" and the
  // reporter records retries>0. Locally 0, so flakiness is visible while you work.
  // Never raise this to make a suite green — see the flake-guard skill.
  retries:       process.env.CI ? 1 : 0,
  workers:       1,     // single worker — prevents concurrent auth collisions
  fullyParallel: false,

  // ── Reporters ───────────────────────────────────────────────────────────────
  //   list               → live terminal output while tests run
  //   versioned-reporter → writes specs/<slug>/report-v{N}.html after each run
  //
  // globalTeardown is NOT registered here and is NOT used for reports.
  reporter: [
    ['list'],
    ['./tests/versioned-reporter.ts'],
  ],

  // ── Browser defaults ────────────────────────────────────────────────────────
  use: {
    headless:           false,               // headed during development
    screenshot:         'on',               // capture for every test
    trace:              'retain-on-failure', // trace zip only on failures
    video:              'off',
    // NO storageState — every test starts with a completely fresh, cookie-free context
  },
});
